name: lint

description: lint feast-postgres, targeting python 3.7

on: [push, pull_request]

jobs:
  lint-python:
    runs-on: [ubuntu-latest]

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -e .[dev]

      - name: Run lint python checks
        run: make lint
