name: test-python-universal

description: Execute multiple versions of feast's universal python plugin integration suite

on: [push, pull_request]

jobs:
  feast-universal-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        feast-version: ["v0.15.0", "v0.15.1", "v0.16.0", "v0.16.1", "v0.17.0", "v0.18.0"]
        python-version: ["3.7"]
        postgres-version: [13]
        os: ["ubuntu-latest"]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: docker
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -e .

      - name: Install feast in a subfolder, run pip install
        run: |
          make install-feast-folder

      - name: Record feast version
        run: python -c 'import feast; print(feast.__version__)'

      - name: Run feast universal tests
        run: |
          make test-python-universal
          

